[project]
name = "pitea"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.7",
    "crypto>=1.4.1",
    "image>=1.5.33",
    "pydub>=0.25.1",
    "wave>=0.0.2",
]
