contador_cache = 1
ult_fecha = "04-02-2025_18:05"
modo_sstv = "MartinM1"
samples_per_sec = 48000
bits = 16
tamanio_fuente = 10
anchura_maxima = 800
ruta_fuente = "../fuentes/ocraregular.ttf"
gpu = "True"
