contador_cache = 0
ult_fecha = "03-02-2025_21:16"
modo_sstv = "MartinM1"
samples_per_sec = 48000
bits = 16
tamanio_fuente = 10
anchura_maxima = 800
ruta_fuente = "../fuentes/ocraregular.ttf"
gpu = "True"
